# Generated by Django 6.0.5 on 2026-05-31 11:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='❓', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Question Categories',
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('text', 'Text/Notes')], default='video', max_length=10)),
                ('media_url', models.URLField(blank=True, help_text='YouTube, Google Drive, or direct URL')),
                ('whatsapp_media_id', models.CharField(blank=True, help_text='WhatsApp media ID if from WA', max_length=200)),
                ('scripture_reference', models.CharField(blank=True, max_length=200)),
                ('sermon_date', models.DateField(default=django.utils.timezone.now)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('questions_enabled', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sermon_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SermonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Sermon Categories',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('whatsapp_number', models.CharField(help_text='International format e.g. 233241234567 (no + or spaces)', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Speaker'), ('failed', 'Failed to Send'), ('answered', 'Answered'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('submitter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=200)),
                ('wa_send_error', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sermons.questioncategory')),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sermons.sermon')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='sermon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sermons.sermoncategory'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='sermons.speaker'),
        ),
    ]
