# Generated by Django 5.0.4 on 2026-05-31 20:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='bio',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
